### ISSUE TITLE
Habitat Plan Issue

### ISSUE THREAD

**Issue by yk-eta** [mozilla/reticulum#691]
reticulum: WARN: Could not find a suitable installed package for 'mozillareality/erlang/23.3.4.18'
   reticulum: ERROR: Resolving 'mozillareality/erlang/23.3.4.18' failed, should this be built first?

look like the package for erlang and elixir in newest update is not available on public

**Comment by Pattersonbl2** [comment]
We are still working to fix this.  Any updates we release for public use will be on the Polycosm branch.

**Comment by johnshaughnessy** [comment]
@yk-eta Are you following the unstable channels on your hubs cloud instance? 

(As far as I'm aware, this should not affect hubs cloud users on the stable channels, so if you're seeing this issue that is surprising and might indicate another problem.)

**Comment by yk-eta** [comment]
@johnshaughnessy I customized reticulum on master branch and recently pulling latest changes, I think on README.md, it does not clarify which branch is for hubs cloud.

**Comment by yk-eta** [comment]
@Pattersonbl2 ok, I will sync polycosm-stable branch next time

**Comment by Pattersonbl2** [comment]
> 

it will just be the polycosm branch located  [here](https://github.com/mozilla/reticulum/blob/polycosm/habitat/plan.sh#L1).  I am not sure if you're running the reticulum locally or with hubs-cloud.  You may run into issues with your code being overwritten by the stable or unstable channel unless you have configured your custom reticulum to track a different channel.

**Comment by johnshaughnessy** [comment]
@yk-eta Yes, it would definitely help to know a bit more about how you're deploying reticulum. Are you building habitat packages yourself for running on your Hubs Cloud instance? Definitely +1 to @Pattersonbl2 's comment above. If you're building reticulum from source, it'll be safer to follow the polycosm branch rather than master. (And if you're also modifying hubs / spoke, the correct branches for those repos are called "hubs-cloud"). We try to keep those branches more stable for hubs cloud users, whereas our main branches update more regularly.

**Comment by johnshaughnessy** [comment]
In any case, I believe this issue should now be resolved because we uploaded the missing erlang/elixir packages and were able to build reticulum packages again. If that's not the case for you @yk-eta please feel free to reopen the issue because I might be mistaken.

**Comment by yk-eta** [comment]
@johnshaughnessy is there any guide for creating AMI with customized reticulum service?
